from enum import Enum

class FuelTypesEnum(Enum):
    Gasohol_91 = "Gasohol 91"
    Gasohol_95 = "Gasohol 95"
    HVO = "HVO"
    Octane_87 = "Octane-87"
    Octane_89 = "Octane-89"
    Octane_90 = "Octane-90"
    Octane_91 = "Octane-91"
    Octane_92 = "Octane-92"
    Octane_93 = "Octane-93"
    Octane_95 = "Octane-95"
    Octane_98 = "Octane-98"
    Octane_100 = "Octane-100"
    Biodiesel = "Biodiesel"
    CNG = "CNG"
    Diesel = "Diesel"
    DieselWithAdditives = "DieselWithAdditives"
    E85 = "E85"
    E10 = "E10"
    E20 = "E20"
    Ethanol = "Ethanol"
    EthanolWithAdditives = "EthanolWithAdditives"
    Gasoline = "Gasoline"
    HighVolumePumps = "HighVolumePumps"
    Hydrogen = "Hydrogen"
    LNG = "LNG"
    LPG = "LPG"
    Midgrade = "Midgrade"
    PayAtPump = "PayAtPump"
    Premium = "Premium"
    PremiumWithAdditives = "PremiumWithAdditives"
    Regular = "Regular"
    RegularWithAdditives = "RegularWithAdditives"
